#!/usr/bin/env swift

import Foundation

/// Bunting Codegen - Generates strongly-typed Swift accessors for feature flags
/// Usage: bunting-codegen <config.json> <output.swift>
///
/// This tool reads a Bunting configuration file and generates Swift code with:
/// - Nested namespaces from flag keys (e.g., "store/enabled" → Bunting.shared.store.enabled)
/// - Type-safe accessors with default values
/// - Documentation comments for each flag
/// - @available annotations for archived flags

// MARK: - Models

struct BuntingConfig: Decodable {
    let flags: [String: Flag]
}

struct Flag: Decodable {
    let type: String
    let description: String?
    let development: EnvironmentConfig
    let staging: EnvironmentConfig
    let production: EnvironmentConfig
}

struct EnvironmentConfig: Decodable {
    // Accept both `default` and `defaultValue` keys from JSON
    let defaultValue: FlagValue

    enum CodingKeys: String, CodingKey {
        case defaultValue = "defaultValue"
        case `default` = "default"
    }

    init(defaultValue: FlagValue) {
        self.defaultValue = defaultValue
    }

    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        if let value = try container.decodeIfPresent(FlagValue.self, forKey: .defaultValue) {
            self.defaultValue = value
        } else if let value = try container.decodeIfPresent(FlagValue.self, forKey: .default) {
            self.defaultValue = value
        } else {
            // If neither key exists, treat as null
            self.defaultValue = .null
        }
    }
}

enum FlagValue: Codable {
    case bool(Bool)
    case string(String)
    case int(Int)
    case double(Double)
    case null

    init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()

        if let bool = try? container.decode(Bool.self) {
            self = .bool(bool)
        } else if let int = try? container.decode(Int.self) {
            self = .int(int)
        } else if let double = try? container.decode(Double.self) {
            self = .double(double)
        } else if let string = try? container.decode(String.self) {
            self = .string(string)
        } else {
            self = .null
        }
    }

    func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .bool(let value): try container.encode(value)
        case .string(let value): try container.encode(value)
        case .int(let value): try container.encode(value)
        case .double(let value): try container.encode(value)
        case .null: try container.encodeNil()
        }
    }
}

// MARK: - Code Generation

struct CodeGenerator {
    let config: BuntingConfig

    func generate() -> String {
        var output = """
            // Generated by Bunting Codegen
            // DO NOT EDIT - This file is automatically generated
            //
            // To regenerate:
            // 1. Update your BuntingConfig.json
            // 2. Rebuild your project

            import Foundation
            import Bunting

            // MARK: - Generated Flag Accessors

            extension Bunting {

            """

        // Group flags by namespace
        let namespaces = groupByNamespace()

        // Generate namespace extensions
        for (namespace, flags) in namespaces.sorted(by: { $0.key < $1.key }) {
            if namespace.isEmpty {
                // Root level flags
                for (key, flag) in flags.sorted(by: { $0.key < $1.key }) {
                    output += generateFlagAccessor(key: key, flag: flag, indent: 1)
                }
            } else {
                // Namespaced flags
                output += generateNamespace(namespace, flags: flags)
            }
        }

        output += "}\n"

        return output
    }

    private func groupByNamespace() -> [String: [String: Flag]] {
        var namespaces: [String: [String: Flag]] = [:]

        for (key, flag) in config.flags {
            let parts = key.split(separator: "/")

            if parts.count == 1 {
                // Root level flag
                namespaces["", default: [:]][key] = flag
            } else {
                // Namespaced flag
                let namespace = String(parts[0])
                let flagName = parts.dropFirst().joined(separator: "_")
                namespaces[namespace, default: [:]][flagName] = flag
            }
        }

        return namespaces
    }

    private func generateNamespace(_ namespace: String, flags: [String: Flag]) -> String {
        let namespaceName = camelCase(namespace.capitalized)

        var output = """

                /// Namespace for '\(namespace)' flags
                var \(namespaceName.prefix(1).lowercased() + namespaceName.dropFirst()): \(namespaceName)Namespace {
                    \(namespaceName)Namespace(bunting: self)
                }

                struct \(namespaceName)Namespace {
                    let bunting: Bunting

            """

        for (key, flag) in flags.sorted(by: { $0.key < $1.key }) {
            output += generateFlagAccessor(
                key: key, flag: flag, indent: 2, fullKey: "\(namespace)/\(key)")
        }

        output += "    }\n"

        return output
    }

    private func generateFlagAccessor(key: String, flag: Flag, indent: Int, fullKey: String? = nil)
        -> String
    {
        let indentStr = String(repeating: "    ", count: indent)
        let propertyName = camelCase(key)
        let actualKey = fullKey ?? key

        // Determine Swift type and default value
        let (swiftType, defaultValue) = getTypeAndDefault(from: flag)

        var output = "\n"

        // Add documentation
        if let description = flag.description {
            output += "\(indentStr)/// \(description)\n"
        }
        output += "\(indentStr)/// Flag key: `\(actualKey)`\n"
        output += "\(indentStr)/// Type: `\(flag.type)`\n"

        // Generate property
        output += "\(indentStr)var \(propertyName): \(swiftType) {\n"
        output += "\(indentStr)    get {\n"

        // Generate the appropriate accessor call
        switch flag.type {
        case "boolean", "bool":
            output +=
                "\(indentStr)        bunting.bool(\"\(actualKey)\", default: \(defaultValue))\n"
        case "string":
            output +=
                "\(indentStr)        bunting.string(\"\(actualKey)\", default: \(defaultValue))\n"
        case "integer", "int":
            output +=
                "\(indentStr)        bunting.int(\"\(actualKey)\", default: \(defaultValue))\n"
        case "double":
            output +=
                "\(indentStr)        bunting.double(\"\(actualKey)\", default: \(defaultValue))\n"
        case "date":
            output +=
                "\(indentStr)        bunting.date(\"\(actualKey)\", default: \(defaultValue))\n"
        case "json":
            output += "\(indentStr)        bunting.jsonData(\"\(actualKey)\")\n"
        default:
            output +=
                "\(indentStr)        bunting.string(\"\(actualKey)\", default: \"\") // Unknown type\n"
        }

        output += "\(indentStr)    }\n"
        output += "\(indentStr)}\n"

        return output
    }

    private func getTypeAndDefault(from flag: Flag) -> (String, String) {
        // Use development default as the seed default
        let defaultValue = flag.development.defaultValue

        switch flag.type {
        case "boolean", "bool":
            if case .bool(let value) = defaultValue {
                return ("Bool", value ? "true" : "false")
            }
            return ("Bool", "false")

        case "string":
            if case .string(let value) = defaultValue {
                return ("String", "\"\(value)\"")
            }
            return ("String", "\"\"")

        case "integer", "int":
            if case .int(let value) = defaultValue {
                return ("Int", "\(value)")
            }
            return ("Int", "0")

        case "double":
            if case .double(let value) = defaultValue {
                return ("Double", "\(value)")
            }
            return ("Double", "0.0")

        case "date":
            return ("Date", "Date()")

        case "json":
            return ("JSONData?", "nil")

        default:
            return ("String", "\"\"")
        }
    }

    private func camelCase(_ string: String) -> String {
        let parts = string.components(separatedBy: CharacterSet.alphanumerics.inverted)
        return parts.enumerated().map { index, part in
            if index == 0 {
                return part.prefix(1).lowercased() + part.dropFirst()
            } else {
                return part.capitalized
            }
        }.joined()
    }
}

// MARK: - Main

func main() {
    let arguments = CommandLine.arguments

    guard arguments.count == 3 else {
        printUsage()
        exit(1)
    }

    let configPath = arguments[1]
    let outputPath = arguments[2]

    do {
        // Load config
        let configURL = URL(fileURLWithPath: configPath)
        let configData = try Data(contentsOf: configURL)
        let config = try JSONDecoder().decode(BuntingConfig.self, from: configData)

        // Generate code
        let generator = CodeGenerator(config: config)
        let generatedCode = generator.generate()

        // Write output
        let outputURL = URL(fileURLWithPath: outputPath)
        try generatedCode.write(to: outputURL, atomically: true, encoding: .utf8)

        print("✅ Generated flag accessors: \(outputPath)")
        print("   Processed \(config.flags.count) flags")

    } catch let error as CocoaError where error.code == .fileReadNoSuchFile {
        fputs("❌ Error: Could not open \(configPath) (No such file)\n", stderr)
        fputs("   • Ensure BuntingConfig.json exists at that path\n", stderr)
        fputs("   • If your project path contains spaces, Xcode will quote arguments automatically;\n", stderr)
        fputs("     but verify the file isn’t missing or excluded by sandbox\n", stderr)
        exit(1)
    } catch {
        fputs("❌ Error: \(error.localizedDescription)\n", stderr)
        exit(1)
    }
}

func printUsage() {
    print(
        """
        Bunting Codegen - Generate strongly-typed flag accessors

        USAGE:
            bunting-codegen <config.json> <output.swift>

        ARGUMENTS:
            config.json    Path to Bunting configuration file
            output.swift   Where to write generated code

        EXAMPLE:
            bunting-codegen BuntingConfig.json BuntingGenerated.swift
        """)
}

main()
