#!/usr/bin/env swift

import Foundation

/// Bunting Codegen - Generates strongly-typed Swift accessors for feature flags
/// Usage: bunting-codegen <config.json> <output.swift>
///
/// This tool reads a Bunting configuration file and generates Swift code with:
/// - Nested namespaces from flag keys (e.g., "store/enabled" → Bunting.shared.store.enabled)
/// - Type-safe accessors with default values
/// - Documentation comments for each flag
/// - @available annotations for archived flags

// MARK: - Models

struct BuntingConfig: Decodable {
    let flags: [String: Flag]
}

struct Flag: Decodable {
    let type: String
    let description: String?
    let development: EnvironmentConfig
    let staging: EnvironmentConfig
    let production: EnvironmentConfig
}

struct EnvironmentConfig: Decodable {
    // Accept both `default` and `defaultValue` keys from JSON
    let defaultValue: FlagValue

    enum CodingKeys: String, CodingKey {
        case defaultValue = "defaultValue"
        case `default` = "default"
    }

    init(defaultValue: FlagValue) {
        self.defaultValue = defaultValue
    }

    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        if let value = try container.decodeIfPresent(FlagValue.self, forKey: .defaultValue) {
            self.defaultValue = value
        } else if let value = try container.decodeIfPresent(FlagValue.self, forKey: .default) {
            self.defaultValue = value
        } else {
            // If neither key exists, treat as null
            self.defaultValue = .null
        }
    }
}

enum FlagValue: Codable {
    case bool(Bool)
    case string(String)
    case int(Int)
    case double(Double)
    case null

    init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()

        if let bool = try? container.decode(Bool.self) {
            self = .bool(bool)
        } else if let int = try? container.decode(Int.self) {
            self = .int(int)
        } else if let double = try? container.decode(Double.self) {
            self = .double(double)
        } else if let string = try? container.decode(String.self) {
            self = .string(string)
        } else {
            self = .null
        }
    }

    func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .bool(let value): try container.encode(value)
        case .string(let value): try container.encode(value)
        case .int(let value): try container.encode(value)
        case .double(let value): try container.encode(value)
        case .null: try container.encodeNil()
        }
    }
}

// MARK: - Code Generation

struct CodeGenerator {
    let config: BuntingConfig

    func generate() -> String {
        var output = """
            // Generated by Bunting Codegen
            // DO NOT EDIT - This file is automatically generated
            //
            // To regenerate:
            // 1. Update your BuntingConfig.json
            // 2. Rebuild your project

            import Foundation
            import Bunting

            // MARK: - Generated Flag Accessors

            extension Bunting {

            """

        // Group flags by namespace
        let namespaces = groupByNamespace()

        // Generate namespace extensions (convenience sync accessors)
        for (namespace, flags) in namespaces.sorted(by: { $0.key < $1.key }) {
            if namespace.isEmpty {
                // Root level flags
                for (key, flag) in flags.sorted(by: { $0.key < $1.key }) {
                    output += generateFlagAccessor(key: key, flag: flag, indent: 1)
                }
            } else {
                // Namespaced flags
                output += generateNamespace(namespace, flags: flags)
            }
        }

        output += "}\n"

        // MARK: - Generated Flag Descriptors (BuntingPaths)
        output += "\n\n// MARK: - Generated Flag Descriptors\n\n"
        output += "extension BuntingPaths {\n\n"

        // Root-level descriptors (no namespace)
        if let rootFlags = namespaces[""] {
            for (key, flag) in rootFlags.sorted(by: { $0.key < $1.key }) {
                output += generateDescriptorProperty(key: key, flag: flag, indent: 1)
            }
        }

        // Namespaced descriptors
        for (namespace, flags) in namespaces.sorted(by: { $0.key < $1.key })
        where namespace.isEmpty == false {
            output += generateDescriptorNamespace(namespace, flags: flags)
        }

        // Add a flat list of all flags for easy UI rendering
        output += "\n    public var allFlags: [FlagListItem] {\n"
        output += "        [\n"

        // Emit list entries for all flags
        var first = true
        for (namespace, flags) in namespaces.sorted(by: { $0.key < $1.key }) {
            for (key, flag) in flags.sorted(by: { $0.key < $1.key }) {
                let fullKey = namespace.isEmpty ? key : "\(namespace)/\(key)"
                output += generateListItem(key: fullKey, flag: flag, isFirst: first)
                first = false
            }
        }

        output += "        ]\n"
        output += "    }\n"

        output += "}\n"

        // FlagDescriptor type is provided by the Bunting library.

        return output
    }

    private func groupByNamespace() -> [String: [String: Flag]] {
        var namespaces: [String: [String: Flag]] = [:]

        for (key, flag) in config.flags {
            let parts = key.split(separator: "/")

            if parts.count == 1 {
                // Root level flag
                namespaces["", default: [:]][key] = flag
            } else {
                // Namespaced flag
                let namespace = String(parts[0])
                let flagName = parts.dropFirst().joined(separator: "_")
                namespaces[namespace, default: [:]][flagName] = flag
            }
        }

        return namespaces
    }

    private func generateNamespace(_ namespace: String, flags: [String: Flag]) -> String {
        let namespaceName = camelCase(namespace.capitalized)

        var output = """

                /// Namespace for '\(namespace)' flags
                var \(namespaceName.prefix(1).lowercased() + namespaceName.dropFirst()): \(namespaceName)Namespace {
                    \(namespaceName)Namespace(self)
                }

                struct \(namespaceName)Namespace {
                    private let bunting: Bunting
            
                    init(_ bunting: Bunting) {
                        self.bunting = bunting
                    }

            """

        for (key, flag) in flags.sorted(by: { $0.key < $1.key }) {
            output += generateFlagAccessor(
                key: key, flag: flag, indent: 2, fullKey: "\(namespace)/\(key)")
        }

        output += "    }\n"

        return output
    }

    private func generateDescriptorNamespace(_ namespace: String, flags: [String: Flag]) -> String {
        let namespaceName = camelCase(namespace.capitalized)

        var output = """

                /// Descriptor namespace for '\(namespace)' flags
                var \(namespaceName.prefix(1).lowercased() + namespaceName.dropFirst()): \(namespaceName)Namespace {
                    \(namespaceName)Namespace(bunting)
                }

                struct \(namespaceName)Namespace {
                    private let bunting: Bunting
            
                    init(_ bunting: Bunting) {
                        self.bunting = bunting
                    }

            """

        for (key, flag) in flags.sorted(by: { $0.key < $1.key }) {
            output += generateDescriptorProperty(
                key: "\(namespace)/\(key)", flag: flag, indent: 2, propertyName: camelCase(key))
        }

        output += "    }\n"

        return output
    }

    private func generateDescriptorProperty(
        key: String,
        flag: Flag,
        indent: Int,
        propertyName: String? = nil
    ) -> String {
        let indentStr = String(repeating: "    ", count: indent)
        let (swiftType, defaultValue) = getTypeAndDefault(from: flag)
        let name = propertyName ?? camelCase(key)

        var output = "\n"
        if let description = flag.description {
            output += "\(indentStr)/// \(description)\n"
        }
        output += "\(indentStr)/// Flag key: `\(key)`\n"
        output += "\(indentStr)var \(name): FlagDescriptor<\(swiftType)> {\n"
        output +=
            "\(indentStr)    FlagDescriptor(key: \"\(key)\", defaultValue: \(defaultValue)) { bunting in\n"

        switch flag.type {
        case "boolean", "bool":
            output += "\(indentStr)        bunting.bool(\"\(key)\", default: \(defaultValue))\n"
        case "string":
            output += "\(indentStr)        bunting.string(\"\(key)\", default: \(defaultValue))\n"
        case "integer", "int":
            output += "\(indentStr)        bunting.int(\"\(key)\", default: \(defaultValue))\n"
        case "double":
            output += "\(indentStr)        bunting.double(\"\(key)\", default: \(defaultValue))\n"
        case "date":
            output += "\(indentStr)        bunting.date(\"\(key)\", default: \(defaultValue))\n"
        case "json":
            output += "\(indentStr)        bunting.jsonData(\"\(key)\")\n"
        default:
            output += "\(indentStr)        bunting.string(\"\(key)\", default: \"\")\n"
        }

        output += "\(indentStr)    }\n"
        output += "\(indentStr)}\n"

        return output
    }

    private func generateListItem(key: String, flag: Flag, isFirst: Bool) -> String {
        let prefix = isFirst ? "            " : "            "
        var body = "\(prefix)FlagListItem(key: \"\(key)\", type: \"\(flag.type)\") { bunting in\n"
        switch flag.type {
        case "boolean", "bool":
            body += "                String(bunting.bool(\"\(key)\", default: \(getDefaultLiteral(flag))))\n"
        case "string":
            body += "                bunting.string(\"\(key)\", default: \(getDefaultLiteral(flag)))\n"
        case "integer", "int":
            body += "                String(bunting.int(\"\(key)\", default: \(getDefaultLiteral(flag))))\n"
        case "double":
            body += "                String(bunting.double(\"\(key)\", default: \(getDefaultLiteral(flag))))\n"
        case "date":
            body += "                ISO8601DateFormatter().string(from: bunting.date(\"\(key)\", default: Date()))\n"
        case "json":
            body += "                (bunting.jsonData(\"\(key)\").flatMap { String(data: $0, encoding: .utf8) } ?? \"<nil>\")\n"
        default:
            body += "                bunting.string(\"\(key)\", default: \"\")\n"
        }
        body += "            },\n"
        return body
    }

    private func getDefaultLiteral(_ flag: Flag) -> String {
        let def = flag.development.defaultValue
        switch flag.type {
        case "boolean", "bool":
            if case .bool(let v) = def { return v ? "true" : "false" }
            return "false"
        case "string":
            if case .string(let v) = def { return "\"\(v)\"" }
            return "\"\""
        case "integer", "int":
            if case .int(let v) = def { return "\(v)" }
            return "0"
        case "double":
            if case .double(let v) = def { return "\(v)" }
            return "0.0"
        case "date":
            return "Date()"
        case "json":
            return "nil"
        default:
            return "\"\""
        }
    }

    private func generateFlagAccessor(key: String, flag: Flag, indent: Int, fullKey: String? = nil)
        -> String
    {
        let indentStr = String(repeating: "    ", count: indent)
        let propertyName = camelCase(key)
        let actualKey = fullKey ?? key

        // Determine Swift type and default value
        let (swiftType, defaultValue) = getTypeAndDefault(from: flag)

        var output = "\n"

        // Add documentation
        if let description = flag.description {
            output += "\(indentStr)/// \(description)\n"
        }
        output += "\(indentStr)/// Flag key: `\(actualKey)`\n"
        output += "\(indentStr)/// Type: `\(flag.type)`\n"

        // Generate property
        output += "\(indentStr)var \(propertyName): \(swiftType) {\n"
        output += "\(indentStr)    get {\n"

        // Generate the appropriate accessor call
        switch flag.type {
        case "boolean", "bool":
            output +=
                "\(indentStr)        bunting.bool(\"\(actualKey)\", default: \(defaultValue))\n"
        case "string":
            output +=
                "\(indentStr)        bunting.string(\"\(actualKey)\", default: \(defaultValue))\n"
        case "integer", "int":
            output +=
                "\(indentStr)        bunting.int(\"\(actualKey)\", default: \(defaultValue))\n"
        case "double":
            output +=
                "\(indentStr)        bunting.double(\"\(actualKey)\", default: \(defaultValue))\n"
        case "date":
            output +=
                "\(indentStr)        bunting.date(\"\(actualKey)\", default: \(defaultValue))\n"
        case "json":
            output += "\(indentStr)        bunting.jsonData(\"\(actualKey)\")\n"
        default:
            output +=
                "\(indentStr)        bunting.string(\"\(actualKey)\", default: \"\") // Unknown type\n"
        }

        output += "\(indentStr)    }\n"
        output += "\(indentStr)}\n"

        return output
    }

    private func getTypeAndDefault(from flag: Flag) -> (String, String) {
        // Use development default as the seed default
        let defaultValue = flag.development.defaultValue

        switch flag.type {
        case "boolean", "bool":
            if case .bool(let value) = defaultValue {
                return ("Bool", value ? "true" : "false")
            }
            return ("Bool", "false")

        case "string":
            if case .string(let value) = defaultValue {
                return ("String", "\"\(value)\"")
            }
            return ("String", "\"\"")

        case "integer", "int":
            if case .int(let value) = defaultValue {
                return ("Int", "\(value)")
            }
            return ("Int", "0")

        case "double":
            if case .double(let value) = defaultValue {
                return ("Double", "\(value)")
            }
            return ("Double", "0.0")

        case "date":
            return ("Date", "Date()")

        case "json":
            return ("JSONData?", "nil")

        default:
            return ("String", "\"\"")
        }
    }

    private func camelCase(_ string: String) -> String {
        let parts = string.components(separatedBy: CharacterSet.alphanumerics.inverted)
        return parts.enumerated().map { index, part in
            if index == 0 {
                return part.prefix(1).lowercased() + part.dropFirst()
            } else {
                return part.capitalized
            }
        }.joined()
    }
}

// MARK: - Fallback Code Generation

func generateFallbackCode() -> String {
    return """
        // Generated by Bunting Codegen (Fallback Mode)
        // No configuration available - using minimal fallback implementation
        //
        // To enable strongly-typed flag accessors:
        // 1. Run: swift package plugin fetch-config
        //    OR place BuntingConfig.json in your project root
        // 2. Rebuild your project
        //
        // You can still use string-based flag access:
        //   let value = Bunting.shared.bool("my/flag", default: false)

        import Foundation
        import Bunting

        // MARK: - Fallback Flag Accessors

        extension Bunting {
            // No flags available - add BuntingConfig.json to generate accessors
        }

        // MARK: - Fallback Flag Descriptors

        /// Base paths structure for @BuntingFlag property wrapper
        public struct BuntingPaths {
            private let bunting: Bunting

            public init(_ bunting: Bunting) {
                self.bunting = bunting
            }
        }

        extension BuntingPaths {
            // No flag descriptors available
            // Add BuntingConfig.json to your project and rebuild to generate strongly-typed accessors
            //
            // For now, use string-based flag access:
            //   @State private var myFlag = Bunting.shared.bool("my/flag", default: false)
        }

        /// Descriptor for a single flag with type information
        public struct FlagDescriptor<T> {
            public let key: String
            public let defaultValue: T
            public let resolve: (Bunting) -> T

            public init(key: String, defaultValue: T, resolve: @escaping (Bunting) -> T) {
                self.key = key
                self.defaultValue = defaultValue
                self.resolve = resolve
            }
        }

        """
}

// MARK: - Main

func main() {
    let arguments = CommandLine.arguments

    guard arguments.count == 3 else {
        printUsage()
        exit(1)
    }

    let configPath = arguments[1]
    let outputPath = arguments[2]

    // Check if config path is empty (signal from plugin that config is missing)
    if configPath.isEmpty {
        // Generate fallback file
        let fallbackCode = generateFallbackCode()
        let outputURL = URL(fileURLWithPath: outputPath)
        do {
            try fallbackCode.write(to: outputURL, atomically: true, encoding: .utf8)
            print("⚠️  Generated fallback accessors (no config available)")
            print("   Add BuntingConfig.json and rebuild to enable strongly-typed flags")
        } catch {
            fputs("❌ Error writing fallback file: \(error.localizedDescription)\n", stderr)
            exit(1)
        }
        exit(0)
    }

    do {
        // Load config
        let configURL = URL(fileURLWithPath: configPath)
        let configData = try Data(contentsOf: configURL)
        let config = try JSONDecoder().decode(BuntingConfig.self, from: configData)

        // Generate code
        let generator = CodeGenerator(config: config)
        let generatedCode = generator.generate()

        // Write output
        let outputURL = URL(fileURLWithPath: outputPath)
        try generatedCode.write(to: outputURL, atomically: true, encoding: .utf8)

        print("✅ Generated flag accessors: \(outputPath)")
        print("   Processed \(config.flags.count) flags")

    } catch let error as CocoaError where error.code == .fileReadNoSuchFile {
        // Config file not found - generate fallback instead of failing
        print("⚠️  Config file not found: \(configPath)")
        print("   Generating fallback accessors to prevent build failure")

        let fallbackCode = generateFallbackCode()
        let outputURL = URL(fileURLWithPath: outputPath)
        do {
            try fallbackCode.write(to: outputURL, atomically: true, encoding: .utf8)
            print("✅ Generated fallback accessors")
            print("   Add BuntingConfig.json and rebuild to enable strongly-typed flags")
        } catch {
            fputs("❌ Error writing fallback file: \(error.localizedDescription)\n", stderr)
            exit(1)
        }
    } catch {
        // JSON decode error or other issue - generate fallback
        print("⚠️  Error processing config: \(error.localizedDescription)")
        print("   Generating fallback accessors to prevent build failure")

        let fallbackCode = generateFallbackCode()
        let outputURL = URL(fileURLWithPath: outputPath)
        do {
            try fallbackCode.write(to: outputURL, atomically: true, encoding: .utf8)
            print("✅ Generated fallback accessors")
            print("   Fix BuntingConfig.json and rebuild to enable strongly-typed flags")
        } catch {
            fputs("❌ Error writing fallback file: \(error.localizedDescription)\n", stderr)
            exit(1)
        }
    }
}

func printUsage() {
    print(
        """
        Bunting Codegen - Generate strongly-typed flag accessors

        USAGE:
            bunting-codegen <config.json> <output.swift>

        ARGUMENTS:
            config.json    Path to Bunting configuration file
            output.swift   Where to write generated code

        EXAMPLE:
            bunting-codegen BuntingConfig.json BuntingGenerated.swift
        """)
}

main()
